name: Abrir issue automática se variável estiver ausente

on:
  workflow_dispatch:

permissions:
  issues: write

jobs:
  check-env-and-create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar se a variável REQUIRED_VAR está definida
        id: check_var
        run: |
          if [ -z "${{ secrets.REQUIRED_VAR }}" ]; then
            echo "VAR_MISSING=true" >> $GITHUB_ENV
          else
            echo "VAR_MISSING=false" >> $GITHUB_ENV
          fi

      - name: Criar issue se REQUIRED_VAR estiver ausente
        if: env.VAR_MISSING == 'true'
        run: |
          echo "Criando issue automática..."
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d '{
              "title": "Variável REQUIRED_VAR ausente no ambiente",
              "body": "O workflow identificou que a variável REQUIRED_VAR não está configurada no ambiente.",
              "labels": ["bug", "ci"]
            }'
