name: Abrir issue automática se variável estiver ausente

on:
  workflow_dispatch:

permissions:
  issues: write

jobs:
  check-and-create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar se REQUIRED_VAR está presente
        id: check_var
        run: |
          if [ -z "${{ secrets.REQUIRED_VAR }}" ]; then
            echo "VAR_MISSING=true" >> $GITHUB_ENV
          else
            echo "VAR_MISSING=false" >> $GITHUB_ENV
          fi

      - name: Verificar se já existe uma issue com o mesmo título
        if: env.VAR_MISSING == 'true'
        id: issue_check
        run: |
          EXISTE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues?state=open&per_page=100" \
            | jq '.[] | select(.title == "Variável REQUIRED_VAR ausente no ambiente")')

          if [ -z "$EXISTE" ]; then
            echo "CRIAR=true" >> $GITHUB_ENV
          else
            echo "CRIAR=false" >> $GITHUB_ENV
            echo "Já existe uma issue aberta para este problema."
          fi

      - name: Criar issue se necessário
        if: env.CRIAR == 'true'
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d '{
              "title": "Variável REQUIRED_VAR ausente no ambiente",
              "body": "O workflow identificou que a variável REQUIRED_VAR não está configurada no ambiente.",
              "labels": ["bug", "ci"]
            }'
