name: Lint and Test

on:
  workflow_call:
    inputs:
      java-version:
        description: JDK a instalar
        required: true
        type: string
      run_tests:
        description: Executar testes?
        required: true
        type: boolean
      run_lint:
        description: Executar lint?
        required: true
        type: boolean

jobs:
  lint:
    if: ${{ inputs.run_lint }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}

      - name: Verificar estilo de código (Checkstyle)
        run: mvn checkstyle:check -Dcheckstyle.failOnViolation=false

  test:
    if: ${{ inputs.run_tests }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java-version }}

      - name: Executar testes automatizados
        run: mvn test