name: Lint and Test

on:
  workflow_call:
    inputs:
      java-version:
        description: Versão do JDK que será instalada
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}

      - name: Verificar estilo de código (Checkstyle)
        run: mvn checkstyle:check -Dcheckstyle.failOnViolation=false

  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java-version }}

      - name: Executar testes automatizados
        run: mvn test