name: Validação Runner Local

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main

jobs:
  checagem-local:
    runs-on: self-hosted
    steps:
      - name: Verificar sistema
        run: |
          echo "=== Informações do Runner ==="
          uname -a

      - name: Instalar Java 17
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
          echo "PATH=$PATH:/usr/lib/jvm/java-17-openjdk-amd64/bin" >> $GITHUB_ENV

      - name: Verificar Java
        run: java -version

      - name: Instalar software adicional (curl)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y curl

      - name: Verificar curl
        run: |
          echo "Versão do curl:"
          curl --version || { echo "curl não encontrado após instalação."; exit 1; }