name: Uso de Variáveis de ambiente e Secrets

on:
  workflow_dispatch:

jobs:
  variaveis-e-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Exibir variáveis de repositório
        run: |
          echo "Modo da aplicação: ${{ vars.APP_MODE }}"
          echo "Contato de suporte: ${{ vars.SUPPORT_EMAIL }}"

      - name: Simular tarefa sensível com secrets
        run: |
          echo "Usando token para autenticação no ambiente de produção..."
          echo "Token: ${{ secrets.PROD_TOKEN }}"
        env:
          PROD_TOKEN: ${{ secrets.PROD_TOKEN }}